apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
data:
  JWT_SECRET: NDdiZTcyMGUzNmQyYTcwMzE1NTJkZjM2MmIwNTViZjJlYWIwMTBiZWZmNTAwZWNmYjYwYTYzZTljODQ4MjM3NWNhOGI2MmI5YmQ3YmMyNzZmZDkzODc1YzAyMmFjMDg5YTUwNjhhYjhiODc0Mjc4ZjY3MTAzNDc5OTJjZjYyMjA0NGU2MTM3ZjcwOGVhOWYzNGY5MDYxMDVkNDU3YjU3ODk4NGJjYjExOTdlNWQ5NWQ3MTdhM2RjMWE3YmY0YmFiODgyZThmNmRiMzQ0YmU4MjQ0NzkwODI5OGMwNWRkNDcwYzg3MDIwZTQxZjM2Y2UyYTY3ODBlNzM4NzgxNmVkMzRhZjM0YTc2ZjgwYzUzMjljNDExZDI3YTU3ZWZmYzcwY2QzNDExY2RmOTM0ZjMyZGViOTNiMGViYjFmZDI3ZDk3OTdjYmFiM2FhMGU2ZWVjMmRjZGMxNmI2YmI0YTZlYTg0MzRiNDZiZTM5ZDY0NWExZWIyNGVlY2UwMjk0OTdjN2IyMmRlMmExZTVmNjRjMDhiODRkOTkxZjUxNGNhOGY2MzM0MmMyOWYzNzZkYTU1NmZmYzVkOGNiM2NkYjU5NjkyZGNhZjhhZDQwNTU5NTFjODFkNTQ5YzVkN2E4Zjc5ODNkZTA2MDRjYmIyM2NkNGFlY2I0MjQzMGMwNTFlNDM=
 
